this["JST"] = this["JST"] || {};

this["JST"]["templates/contactus.handlebars"] = function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape;
with (obj) {
__p += '\n<div class="locate-us">\n\t<h1> Address 1 </h1>\n\t<div id="address-map" class="map"></div>\n\t<div class="address-detail">\n\n\t\t<div>\n\t\t\t<img src="/images/logo.png" />\n\t\t</div>\n\t\t<h3> Jalpa Dance Academy </h3>\n\t\t<div>\n\t\t\t<b>Suwanee:</b>\n\t\t\t<br/> 6365 Read Road\n\t\t\t<br/> Suwanee, GA 30024\n\t\t</div>\n\t\t<div>\n\t\t\tIf you have any question, please feel free to contact us\n\t\t</div>\n\t\t<br/>\n\t\t<div>\n\t\t\tEmail :\n\t\t\t<a href="mailto:jalpa.dance.academy@gmail.com">\n\t\t\t\tjalpa.dance.academy@gmail.com\n\t\t\t</a>\n\t\t</div>\n\t\t<div>\n\t\t\tPhone :\n\t\t\t<a href="tel:(678) 481-7207">\n\t\t\t\t(678) 481-7207\n\t\t\t</a>\n\t\t</div>\t\n\t</div>\n</div>\n\n<div class="locate-us">\n\t<h1> Address 2 </h1>\n\t<div id="address-map-1" class="map"></div>\n\t<div class="address-detail">\n\n\t\t<div>\n\t\t\t<img src="/images/logo.png" />\n\t\t</div>\n\t\t<h3> Jalpa Dance Academy </h3>\n\t\t<div>\n\t\t\t<b>Buford:</b>\n\t\t\t<br/> 4296 Old Suwanee Road\n\t\t\t<br/> Suite 4 Buford, GA 30518\n\t\t</div>\n\t\t<br/>\n\t\t<div>\n\t\t\tIf you have any question, please feel free to contact us\n\t\t</div>\n\t\t<br/>\n\t\t<div>\n\t\t\tEmail :\n\t\t\t<a href="mailto:jalpa.dance.academy@gmail.com">\n\t\t\t\tjalpa.dance.academy@gmail.com\n\t\t\t</a>\n\t\t</div>\n\t\t<div>\n\t\t\tPhone :\n\t\t\t<a href="tel:(678) 481-7207">\n\t\t\t\t(678) 481-7207\n\t\t\t</a>\n\t\t</div>\n\t</div>\n</div>\n\n<script>\n\tfunction initMap() {\n\t\tvar address1 = { lat: 34.0784978, lng: -84.1347716 },\n\t\t\taddress2 = { lat: 34.0845577, lng: -84.0308172 }\n\n\t\tvar map = new google.maps.Map(document.getElementById(\'address-map\'), {\n\t\t\tzoom: 10,\n\t\t\tcenter: address1\n\t\t});\n\n\t\tvar map1 = new google.maps.Map(document.getElementById(\'address-map-1\'), {\n\t\t\tzoom: 10,\n\t\t\tcenter: address2\n\t\t});\n\n\t\tvar marker = new google.maps.Marker({\n\t\t\tposition: address1,\n\t\t\tmap: map\n\t\t});\n\t\tvar marker2 = new google.maps.Marker({\n\t\t\tposition: address2,\n\t\t\tmap: map1\n\t\t})\n\t}\n</script>\n\n<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-OJo_BS_LEeMdzIwq30RE7ZUnE6uuDW4&callback=initMap">\n</script>';

}
return __p
};