this["JST"] = this["JST"] || {};

this["JST"]["templates/medinfoTerms.handlebars"] = function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape;
with (obj) {
__p += '<div class="patients-tab">\n\t<div class="info-text">\n        Terms and Types\n\t</div>\n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n\t\t\tAre “medical marijuana” and “medical cannabis” the same thing?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n\t\t\tYes. Cannabis is the medical term for marijuana.\n\t\t</div>\n\n\t</div>\n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n\t\t\tWhat are cannabinoids?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n\t\t\tCannabinoids are chemicals found in cannabis. THC and CBD are the two cannabinoids used for\n            medical treatment.\n\t\t</div>\n\n\t</div>\n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n            Do cannabinoids get people “high”?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n\t\t\tTHC is the mind-altering ingredient in marijuana that can make people “high.” CBD does not\n            have this effect on patients.\n\t\t</div>\n\n\t</div> \n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n\t\t\tDoes the human body also naturally produce cannabinoids?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n            Yes. These chemicals improve concentration, pain tolerance, memory and other important daily\n            functions.\n\t\t</div>\n\t</div> \n\n\n    <div class="question-type">\n\n            <div class="header-text">\n                Are cannabinoids dangerous?\n            </div>\n\n            <div class="sub-header-text">\n                When misused, these chemicals can have serious side effects. This is why patients must \n                be under a physician\'s supervision.\n            </div>\n    </div>\n\n    <div class="question-type">\n\n            <div class="header-text">\n                What do the terms indica, sativa, and hybrid mean?\n            </div>\n\n            <div class="sub-header-text">\n                Indica and sativa are different types of cannabis. A hybrid is a combination of the two types.\n            </div>\n    </div>  \n\n    <div class="question-type">\n\n            <div class="header-text">\n                What is the difference between indica and sativa strands of cannabis?\n            </div>\n\n            <div class="sub-header-text">\n                Indica cannabis, which has a high level of THC, tends to make people feel relaxed. Sativa\n                cannabis, which has a high level of CBD, tends to make people feel energized. (Hybrids fall\n                somewhere in the middle.)\n            </div>\n    </div>\n</div>';

}
return __p
};

this["JST"]["templates/medinfoUses.handlebars"] = function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape;
with (obj) {
__p += '<div class="patients-tab">\n\t<div class="info-text">\n\t\tMedical Uses\n\t</div>\n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n\t\t\tWhat are the medical uses for THC?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n\t\t\tTHC increases appetite and reduces nausea. This is important for patients with certain medical\n            conditions or those undergoing chemotherapy. THC can also decrease pain, inflammation, and\n            problems with muscle control.\n\t\t</div>\n\n\t</div>\n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n\t\t\tWho determines what type of medical cannabis I need?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n            Dr. Patel will determine what treatment is best for you based on your diagnosis, medical history,\n            and symptoms.\n\t\t</div>\n\n\t</div>\n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n            Is medical marijuana safely manufactured and inspected for purity in Florida?\n\t\t</div>\n\n\t\t<div class="sub-header-text">\n            Yes. The state has established rules to make sure all medical cannabis is properly manufactured\n            and inspected.\n\t\t</div>\n\n\t</div> \n\n\t<div class="question-type">\n\n\t\t<div class="header-text">\n\t\t\tCan medical marijuana have negative side effects?   \n\t\t</div>\n\n\t\t<div class="sub-header-text">\n            Sometimes. Dr. Patel will carefully monitor your ongoing health situation to make sure medical\n            cannabis is a good choice for you.\n\t\t</div>\n\t</div> \n\n\n    <div class="question-type">\n\n            <div class="header-text">\n                Is medical marijuana as potentially addictive and destructive to my health as opioid pain\n                medications?\n            </div>\n\n            <div class="sub-header-text">\n                No. In fact, research shows that medical marijuana can help patients reduce use of dangerous\n                opiods.\n            </div>\n    </div>\n\n</div>';

}
return __p
};