this["JST"] = this["JST"] || {};

this["JST"]["templates/team.handlebars"] = function(obj) {
obj || (obj = {});
var __t, __p = '', __e = _.escape;
with (obj) {
__p += '<div class="team-tab" itemscope itemtype="http://schema.org/Physician">\n\n    <div class="doc-image">\n        <img itemprop="image" src="/images/tanmay.jpg" />\n    </div>\n\n    <div class="team-text-wrapper">\n        <h3 itemprop="name">\n            Tanmay Patel, MD\n        </h3>\n\n        <p itemprop="description">\n\n            Tanmay Patel, MD is a board\n            \n            <span itemprop="medicalSpecialty" itemscope itemtype="https://schema.org/medicalSpecialty">\n                 <span itemprop="description"> certified internist </span> \n            </span>     \n            with over 15 years of clinical\n            experience. Throughout his career he has served and treated many patients in\n            pain and with chronic debilitating diseases. Recent Legalization of Medical\n            Cannabis in Florida now provided another treatment options for these patients.\n            Dr. Patel compassion and expertise has been the impetus for \n                <span itemscope itemtype="http://schema.org/Hospital">\n                    <span itemprop="name"> Natural Clinic MD </span>\n                </span>\n            to be created.\n        </p>\n\n        <p>\n            Medical Cannabis has beneficial benefits on the body. However Like any\n            treatment, There are risks and benefits. As quality of life and symptom relief are\n            critical, Dr. Patel will offer a \n            \n            <a href="/get-info">\n                <b>FREE TELEPHONIC CONSULTATION</b>\n            </a>   \n            to see if you\n            would qualify for Medical cannabis under the state current Law.\n        </p>\n\n        <p>\n            It is our goal to provide quality medical care to patients with end stage cancer,\n            Parkinson’s diseases, Multiple Sclerosis, Post traumatic Stress Disorder and\n            other chronic debilitating conditions. Please visit our website for more\n            information on how we can best serve you and your family.\n        </p>\n    </div>\n\n</div>';

}
return __p
};